### PR TITLE
Use jatos.submitResultData instead of jatos.appendResultData

### PR DESCRIPTION
**Pull request by kristian-lange**
Fixing issues with empty result data in JATOS due to premature finished study runs:
https://github.com/shyras/osweb/issues/160

### CODE REVIEW

**Comment by smathot** [comment]
Hi Kristian,

Thanks for this. Just for my understanding: does this also *change* the behavior, or does it only fix broken behavior? Specifically, in shyras/osweb#160 you suggest that one solution is to save all data at the end of the experiment, instead of after every trial. This solution is not acceptable to me, because it's important that partial data is also saved. So could you describe what your fix does exactly?

Cheers!
Sebastiaan

**Review by dschreij — COMMENTED** [review]
As far as I can see from http://www.jatos.org/jatos.js-Reference.html, `submitResultData()` sends all results up till now to the server overwriting the data already stored. This means the data is still sent after each trial (or logger instance) but this also means that *all* data logged up to that point is sent to the server again at each call of submitResultsData. I foresee quite some problems when the transfer size gets quite larger and will take some time, so  I don't see this approach as ideal.

**Comment by dschreij** [comment]
Thanks for submitting a PR  Kristian. I agree this issue needs to be resolved rather sooner than later. I have tried to wrap my head around it too but couldn't come up with a good solution yet. The best would be to wait until the `appendResultData` call is finished and then progress with the experiment, but this potentially increases inter-trial times if this takes a while. As Sebastiaan said, logging the data locally and sending it all at once at the end of the experiment is not really a viable option. This PR seems to realize something in between, but I'm worried that sending all data that has been logged locally over at each submitResultData call, will result in really large request sizes and data transfer sizes after each trial.  I think this will be problematic for people with slower connections, or costly if they used metered connections.

**Comment by kristian-lange** [comment]
Hi everyone! And I thought I could do an easy fix of this issue. Sigh - I was mistaken ;).

**Comment by kristian-lange** [comment]
Hi everyone! And I thought I could do an easy fix of the issue. I was mistaken ;)

@smathot You are correct. This fix sends all data at the end of the experiment. All in other calls of the send function just attach the result data to the variable jatosResultData. And then in the end jatosResultData is send with submitResultData.

@dschreij There is only one sending of the data. It's in the end of the experiement. There is no accumulation of data and only one request to the JATOS server.

But I can see your point. You want to save intermediate result data in order to prevent data loss if an experiment fails for what ever reasons in the end, which could prevent calling the final submitResultData. 

I can only see one other fix and this is what @dschreij already proposed
> The best would be to wait until the appendResultData call is finished and then progress with the experiment

and yes, he's right with

> but this potentially increases inter-trial times if this takes a while

.

I'm thinking about a solution on jatos.js' side: I could change jatos.js in a way that jatos.appendResultData doesn't submit directly to JATOS but adds the data to some kind of **queue**. Then some web worker could submit them one-by-one in the background (all in the client-side) without blocking the main thread (your OSWeb experiment). Additionally, all jatos.js functions that finish a component/study have to be changed that they wait for this worker to be finished before going on. For this solution you guys wouldn't have to change anything on your side.

**Comment by dschreij** [comment]
Thanks for clearing that up Kristian. In that case, I think the solution you mentioned at the end would indeed be one of the best. I have been thinking of a way to wait until the request to Jatos is finished (I guess `appendResultData` returns a promise or can be provided a callback), but the codebase of osweb currently is too complicated (or rather a mess) to handle async functions or pause execution until they are finished. If this would be easily implementable, it would have been a viable option for me too. We could have issued a warning that ITI's in osweb are unreliable and should not be used as  a factor in an experiment.

**Comment by smathot** [comment]
I agree that implementing this in JATOS would be ideal. Partly this is laziness because it's obviously the easy way out for us :-) But also because I think many other software packages will face the same issue. Sending data one trial at a time is—and about that I feel strongly—the way it should be, and sending data only at the end is not. So there should be some easy way to accomplish this.

**Comment by kristian-lange-tw** [comment]
Okay, then I'll work on the queue-in-the-background solution ;)

**Comment by smathot** [comment]
Ok, I'll close this PR then, and then we'll leave shyras/osweb#160 open for reference.

**Comment by dschreij** [comment]
We have for now created another implementation of this solution (using submitResultData), see https://github.com/smathot/opensesame-extension-osweb/pull/15. Still, I'm still an avid proponent of sending data over incrementally, because I predict long waits or a high chance of errors when data sets grow large and have to be sent over completely at the end.

**Pull request closed without merging**
